# Default config for SimpleAuth plugin

#Allows registering new accounts by players.
#If disabled, you can still register new accouts using other plugins.
allowRegister: true

#Sets the data provider (yaml, sqlite3, mysql, none).
#Only use none when there is another plugin that will integrate its dataProvider with SimpleAuth
#Be aware that data is not automatically moved between data providers.
dataProvider: yaml
dataProviderSettings: []

#If enabled, existing logged-in accounts won't be kicked if a new player joins with the same name
#TODO: Add permission
forceSingleSession: true

#Sets the minimum amount of characters to be used when registering a new account
minPasswordLength: 6

#If enabled, accounts that are using the same IP when logging in again will be automatically authenticated
#TODO: Add permission
authenticateByLastIP: false

#Number of seconds to wait for a player to be authenticated. If false, disables the timeout
#TODO
authenticateTimeout: 120

#TODO: Make this a permission (guest)
allowChat: true